name: Makefile CI

on:
  push:
    branches: "**"
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Instal dependencies
      run: sudo apt-get install ragel check dejagnu tcllib pv
    - name: Build frob and unit tests
      run: make frob ut
    - name: Execute all tests
      run: make test
